### ISSUE TITLE
instructions on how to build locally are missing, and cargo install fails

### ISSUE THREAD

**Issue by stockh0lm** [msfjarvis/adnix-rs#46]
This is the error that i get:

cargo install adnix
    Updating crates.io index
  Installing adnix v0.4.1
error: failed to compile `adnix v0.4.1`, intermediate artifacts can be found at `/tmp/cargo-installTrQNX4`

Caused by:
  failed to parse lock file at: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/adnix-0.4.1/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`

**Comment by stockh0lm** [comment]
this could be an issue with an old version of cargo on debian stable.

**Comment by msfjarvis** [comment]
Looks like this issue slipped through the cracks. You're correct, the issue is your version of the Rust compiler. The MSRV of this crate would currently be 1.53.0, since that is where [version 3 of Cargo lockfiles](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#changed-4) was introduced.
